# Generated by Django 5.1.2 on 2024-10-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="tutor_email",
        ),
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
