# Generated by Django 5.1.2 on 2024-10-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_name_classes_csci_alphanumeric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tutoring_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Classes that the tutor is able to tutor (Hold down Control/Command to select more than one)",
                to="accounts.classes",
            ),
        ),
    ]
