# Generated by Django 5.1.2 on 2024-10-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_tutoringhour"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_TA",
            field=models.BooleanField(default=False, help_text="Is the user a TA?"),
        ),
    ]
