# Generated by Django 5.1.2 on 2024-10-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_is_ta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="credit_standing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Freshman", "Freshman"),
                    ("Sophomore", "Sophomore"),
                    ("Junior", "Junior"),
                    ("Senior", "Senior"),
                    ("Postgraduate", "Postgraduate"),
                ],
                help_text="Credit standing of the tutor",
                max_length=50,
                null=True,
            ),
        ),
    ]
