# Generated by Django 5.1.2 on 2024-10-15 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_tutoringhour_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoringhour",
            name="hour",
            field=models.TimeField(
                choices=[
                    (datetime.time(7, 0), "7:00"),
                    (datetime.time(8, 0), "8:00"),
                    (datetime.time(9, 0), "9:00"),
                    (datetime.time(10, 0), "10:00"),
                    (datetime.time(11, 0), "11:00"),
                    (datetime.time(12, 0), "12:00"),
                    (datetime.time(13, 0), "13:00"),
                    (datetime.time(14, 0), "14:00"),
                    (datetime.time(15, 0), "15:00"),
                    (datetime.time(16, 0), "16:00"),
                    (datetime.time(17, 0), "17:00"),
                    (datetime.time(18, 0), "18:00"),
                    (datetime.time(19, 0), "19:00"),
                    (datetime.time(20, 0), "20:00"),
                ]
            ),
        ),
    ]
